version: '3.8'
services:
  ccgl-analytics:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8501:8501"
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports
      - ../logs:/app/logs